{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "cd8bc676-c1ce-4b07-90dc-69867dd11c0a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "Collecting streamlit_jupyter\n",
      "  Downloading streamlit_jupyter-0.2.1-py3-none-any.whl.metadata (8.1 kB)\n",
      "Collecting fastcore (from streamlit_jupyter)\n",
      "  Downloading fastcore-1.7.15-py3-none-any.whl.metadata (3.5 kB)\n",
      "Collecting ipywidgets==7.7.2 (from streamlit_jupyter)\n",
      "  Downloading ipywidgets-7.7.2-py2.py3-none-any.whl.metadata (1.9 kB)\n",
      "Requirement already satisfied: jupyter in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit_jupyter) (1.1.0)\n",
      "Collecting stqdm (from streamlit_jupyter)\n",
      "  Downloading stqdm-0.0.5-py3-none-any.whl.metadata (3.0 kB)\n",
      "Requirement already satisfied: streamlit>=1.19 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit_jupyter) (1.39.0)\n",
      "Collecting tabulate (from streamlit_jupyter)\n",
      "  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)\n",
      "Collecting tqdm (from streamlit_jupyter)\n",
      "  Downloading tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (6.29.5)\n",
      "Collecting ipython-genutils~=0.2.0 (from ipywidgets==7.7.2->streamlit_jupyter)\n",
      "  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)\n",
      "Requirement already satisfied: traitlets>=4.3.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (5.14.3)\n",
      "Collecting widgetsnbextension~=3.6.0 (from ipywidgets==7.7.2->streamlit_jupyter)\n",
      "  Downloading widgetsnbextension-3.6.9-py2.py3-none-any.whl.metadata (1.3 kB)\n",
      "Requirement already satisfied: ipython>=4.0.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipywidgets==7.7.2->streamlit_jupyter) (8.26.0)\n",
      "Collecting jupyterlab-widgets<3,>=1.0.0 (from ipywidgets==7.7.2->streamlit_jupyter)\n",
      "  Downloading jupyterlab_widgets-1.1.10-py3-none-any.whl.metadata (3.7 kB)\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (5.4.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (1.8.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (5.5.0)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (8.1.7)\n",
      "Requirement already satisfied: numpy<3,>=1.20 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (1.26.4)\n",
      "Requirement already satisfied: packaging<25,>=20 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (24.1)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (2.2.2)\n",
      "Requirement already satisfied: pillow<11,>=7.1.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (10.4.0)\n",
      "Requirement already satisfied: protobuf<6,>=3.20 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (4.25.4)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (17.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (2.32.3)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (13.8.0)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (9.0.0)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (4.12.2)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (3.1.43)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (0.9.1)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (6.4.1)\n",
      "Requirement already satisfied: watchdog<6,>=2.1.5 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from streamlit>=1.19->streamlit_jupyter) (5.0.3)\n",
      "Requirement already satisfied: notebook in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter->streamlit_jupyter) (7.2.2)\n",
      "Requirement already satisfied: jupyter-console in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter->streamlit_jupyter) (6.6.3)\n",
      "Requirement already satisfied: nbconvert in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter->streamlit_jupyter) (7.16.4)\n",
      "Requirement already satisfied: jupyterlab in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter->streamlit_jupyter) (4.2.5)\n",
      "Requirement already satisfied: colorama in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from tqdm->streamlit_jupyter) (0.4.6)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (3.1.4)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (4.23.0)\n",
      "Requirement already satisfied: narwhals>=1.5.2 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (1.9.3)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.19->streamlit_jupyter) (4.0.11)\n",
      "Requirement already satisfied: comm>=0.1.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (0.2.2)\n",
      "Requirement already satisfied: debugpy>=1.6.5 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (1.8.5)\n",
      "Requirement already satisfied: jupyter-client>=6.1.12 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (8.6.2)\n",
      "Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (5.7.2)\n",
      "Requirement already satisfied: matplotlib-inline>=0.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (0.1.7)\n",
      "Requirement already satisfied: nest-asyncio in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (1.6.0)\n",
      "Requirement already satisfied: psutil in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (6.0.0)\n",
      "Requirement already satisfied: pyzmq>=24 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (26.2.0)\n",
      "Requirement already satisfied: decorator in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (5.1.1)\n",
      "Requirement already satisfied: jedi>=0.16 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.19.1)\n",
      "Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (3.0.47)\n",
      "Requirement already satisfied: pygments>=2.4.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (2.18.0)\n",
      "Requirement already satisfied: stack-data in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.6.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from pandas<3,>=1.4.0->streamlit>=1.19->streamlit_jupyter) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from pandas<3,>=1.4.0->streamlit>=1.19->streamlit_jupyter) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from pandas<3,>=1.4.0->streamlit>=1.19->streamlit_jupyter) (2024.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (3.8)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from requests<3,>=2.27->streamlit>=1.19->streamlit_jupyter) (2024.8.30)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from rich<14,>=10.14.0->streamlit>=1.19->streamlit_jupyter) (3.0.0)\n",
      "Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from notebook->jupyter->streamlit_jupyter) (2.14.2)\n",
      "Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from notebook->jupyter->streamlit_jupyter) (2.27.3)\n",
      "Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from notebook->jupyter->streamlit_jupyter) (0.2.4)\n",
      "Requirement already satisfied: async-lru>=1.0.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyterlab->jupyter->streamlit_jupyter) (2.0.4)\n",
      "Requirement already satisfied: httpx>=0.25.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyterlab->jupyter->streamlit_jupyter) (0.27.2)\n",
      "Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyterlab->jupyter->streamlit_jupyter) (2.2.5)\n",
      "Requirement already satisfied: setuptools>=40.1.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyterlab->jupyter->streamlit_jupyter) (74.0.0)\n",
      "Requirement already satisfied: beautifulsoup4 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (4.12.3)\n",
      "Requirement already satisfied: bleach!=5.0.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (6.1.0)\n",
      "Requirement already satisfied: defusedxml in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (0.7.1)\n",
      "Requirement already satisfied: jupyterlab-pygments in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (0.3.0)\n",
      "Requirement already satisfied: markupsafe>=2.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (2.1.5)\n",
      "Requirement already satisfied: mistune<4,>=2.0.3 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (3.0.2)\n",
      "Requirement already satisfied: nbclient>=0.5.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (0.10.0)\n",
      "Requirement already satisfied: nbformat>=5.7 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (5.10.4)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (1.5.1)\n",
      "Requirement already satisfied: tinycss2 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbconvert->jupyter->streamlit_jupyter) (1.3.0)\n",
      "Requirement already satisfied: six>=1.9.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from bleach!=5.0.0->nbconvert->jupyter->streamlit_jupyter) (1.16.0)\n",
      "Requirement already satisfied: webencodings in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from bleach!=5.0.0->nbconvert->jupyter->streamlit_jupyter) (0.5.1)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.19->streamlit_jupyter) (5.0.1)\n",
      "Requirement already satisfied: anyio in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from httpx>=0.25.0->jupyterlab->jupyter->streamlit_jupyter) (4.4.0)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from httpx>=0.25.0->jupyterlab->jupyter->streamlit_jupyter) (1.0.5)\n",
      "Requirement already satisfied: sniffio in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from httpx>=0.25.0->jupyterlab->jupyter->streamlit_jupyter) (1.3.1)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter->streamlit_jupyter) (0.14.0)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.8.4)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (24.2.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (2023.12.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (0.35.1)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.19->streamlit_jupyter) (0.20.0)\n",
      "Requirement already satisfied: platformdirs>=2.5 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (4.2.2)\n",
      "Requirement already satisfied: pywin32>=300 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=4.5.1->ipywidgets==7.7.2->streamlit_jupyter) (306)\n",
      "Requirement already satisfied: argon2-cffi>=21.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (23.1.0)\n",
      "Requirement already satisfied: jupyter-events>=0.9.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.10.0)\n",
      "Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.5.3)\n",
      "Requirement already satisfied: overrides>=5.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (7.7.0)\n",
      "Requirement already satisfied: prometheus-client>=0.9 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.20.0)\n",
      "Requirement already satisfied: pywinpty>=2.0.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.0.13)\n",
      "Requirement already satisfied: send2trash>=1.8.2 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.8.3)\n",
      "Requirement already satisfied: terminado>=0.8.3 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.18.1)\n",
      "Requirement already satisfied: websocket-client>=1.7 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.8.0)\n",
      "Requirement already satisfied: babel>=2.10 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter->streamlit_jupyter) (2.16.0)\n",
      "Requirement already satisfied: json5>=0.9.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter->streamlit_jupyter) (0.9.25)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit>=1.19->streamlit_jupyter) (0.1.2)\n",
      "Requirement already satisfied: fastjsonschema>=2.15 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from nbformat>=5.7->nbconvert->jupyter->streamlit_jupyter) (2.20.0)\n",
      "Requirement already satisfied: wcwidth in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.2.13)\n",
      "Requirement already satisfied: soupsieve>1.2 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from beautifulsoup4->nbconvert->jupyter->streamlit_jupyter) (2.6)\n",
      "Requirement already satisfied: executing>=1.2.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from stack-data->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (2.0.1)\n",
      "Requirement already satisfied: asttokens>=2.1.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from stack-data->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (2.4.1)\n",
      "Requirement already satisfied: pure-eval in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from stack-data->ipython>=4.0.0->ipywidgets==7.7.2->streamlit_jupyter) (0.2.3)\n",
      "Requirement already satisfied: argon2-cffi-bindings in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (21.2.0)\n",
      "Requirement already satisfied: python-json-logger>=2.0.4 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.0.7)\n",
      "Requirement already satisfied: pyyaml>=5.3 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (6.0.2)\n",
      "Requirement already satisfied: rfc3339-validator in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.1.4)\n",
      "Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (0.1.1)\n",
      "Requirement already satisfied: fqdn in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.5.1)\n",
      "Requirement already satisfied: isoduration in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (20.11.0)\n",
      "Requirement already satisfied: jsonpointer>1.13 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (3.0.0)\n",
      "Requirement already satisfied: uri-template in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.3.0)\n",
      "Requirement already satisfied: webcolors>=24.6.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (24.8.0)\n",
      "Requirement already satisfied: cffi>=1.0.1 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.17.0)\n",
      "Requirement already satisfied: pycparser in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.22)\n",
      "Requirement already satisfied: arrow>=0.15.0 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (1.3.0)\n",
      "Requirement already satisfied: types-python-dateutil>=2.8.10 in c:\\users\\neelp\\appdata\\roaming\\python\\python312\\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter->streamlit_jupyter) (2.9.0.20240821)\n",
      "Downloading streamlit_jupyter-0.2.1-py3-none-any.whl (13 kB)\n",
      "Downloading ipywidgets-7.7.2-py2.py3-none-any.whl (123 kB)\n",
      "Downloading fastcore-1.7.15-py3-none-any.whl (81 kB)\n",
      "Downloading stqdm-0.0.5-py3-none-any.whl (11 kB)\n",
      "Downloading tqdm-4.66.5-py3-none-any.whl (78 kB)\n",
      "Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)\n",
      "Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)\n",
      "Downloading jupyterlab_widgets-1.1.10-py3-none-any.whl (238 kB)\n",
      "Downloading widgetsnbextension-3.6.9-py2.py3-none-any.whl (1.5 MB)\n",
      "   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--\n",
      "   ---------------------------------------- 1.5/1.5 MB 8.2 MB/s eta 0:00:00\n",
      "Installing collected packages: ipython-genutils, tqdm, tabulate, jupyterlab-widgets, fastcore, stqdm, widgetsnbextension, ipywidgets, streamlit_jupyter\n",
      "  Attempting uninstall: jupyterlab-widgets\n",
      "    Found existing installation: jupyterlab_widgets 3.0.13\n",
      "    Uninstalling jupyterlab_widgets-3.0.13:\n",
      "      Successfully uninstalled jupyterlab_widgets-3.0.13\n",
      "  Attempting uninstall: widgetsnbextension\n",
      "    Found existing installation: widgetsnbextension 4.0.13\n",
      "    Uninstalling widgetsnbextension-4.0.13:\n",
      "      Successfully uninstalled widgetsnbextension-4.0.13\n",
      "  Attempting uninstall: ipywidgets\n",
      "    Found existing installation: ipywidgets 8.1.5\n",
      "    Uninstalling ipywidgets-8.1.5:\n",
      "      Successfully uninstalled ipywidgets-8.1.5\n",
      "Successfully installed fastcore-1.7.15 ipython-genutils-0.2.0 ipywidgets-7.7.2 jupyterlab-widgets-1.1.10 stqdm-0.0.5 streamlit_jupyter-0.2.1 tabulate-0.9.0 tqdm-4.66.5 widgetsnbextension-3.6.9\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  WARNING: The script tqdm.exe is installed in 'C:\\Users\\neelp\\AppData\\Roaming\\Python\\Python312\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "  WARNING: The script tabulate.exe is installed in 'C:\\Users\\neelp\\AppData\\Roaming\\Python\\Python312\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
      "  WARNING: The scripts py2pyi.exe and replace_wildcards.exe are installed in 'C:\\Users\\neelp\\AppData\\Roaming\\Python\\Python312\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit_jupyter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "a083ac9b-fa39-4c31-ac0c-a53f94ab3475",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-10-14 21:18:09.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.326 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.326 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.328 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.332 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.332 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.338 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.340 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.341 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.342 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.344 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.345 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.346 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.347 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.347 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.348 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.349 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.351 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.351 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.353 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.353 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.354 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.356 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.357 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.358 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.360 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.366 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.369 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.379 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.380 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.380 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.380 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.380 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.380 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.380 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.384 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.384 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.389 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.390 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.393 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.393 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.396 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.396 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.398 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.399 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.400 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.400 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.401 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-10-14 21:18:09.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib  # You can also use pickle if you have saved the model\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.ensemble import VotingClassifier\n",
    "\n",
    "# Load the trained ensemble model (assuming it's saved as 'ensemble_model.pkl')\n",
    "# You can save it after training as: joblib.dump(ensemble_model, 'ensemble_model.pkl')\n",
    "ensemble_model = joblib.load('ensemble_model.pkl')  # Update with correct path\n",
    "\n",
    "# Load the dataset to scale the input data correctly\n",
    "data = pd.read_csv('heart_disease_data.csv')\n",
    "\n",
    "# Feature scaling (use the same scaler you used during training)\n",
    "scaler = StandardScaler()\n",
    "X = data.drop('target', axis=1)\n",
    "scaler.fit(X)\n",
    "\n",
    "# Function to predict heart disease\n",
    "def predict_heart_disease(input_features):\n",
    "    input_array = np.array(input_features).reshape(1, -1)\n",
    "    scaled_input = scaler.transform(input_array)\n",
    "    prediction = ensemble_model.predict(scaled_input)\n",
    "    return 'Heart Disease' if prediction[0] == 1 else 'No Heart Disease'\n",
    "\n",
    "# Streamlit Front End\n",
    "st.title('Heart Disease Prediction App')\n",
    "\n",
    "# Define input fields for user input\n",
    "st.header('Input Patient Data for Prediction')\n",
    "\n",
    "age = st.number_input('Age', min_value=1, max_value=120, value=30)\n",
    "sex = st.selectbox('Sex (1 = Male, 0 = Female)', [1, 0])\n",
    "cp = st.selectbox('Chest Pain Type (0 = Typical, 1 = Atypical, 2 = Non-Anginal, 3 = Asymptomatic)', [0, 1, 2, 3])\n",
    "trestbps = st.number_input('Resting Blood Pressure', min_value=80, max_value=200, value=120)\n",
    "chol = st.number_input('Serum Cholestoral in mg/dl', min_value=100, max_value=600, value=200)\n",
    "fbs = st.selectbox('Fasting Blood Sugar > 120 mg/dl (1 = True, 0 = False)', [1, 0])\n",
    "restecg = st.selectbox('Resting Electrocardiographic Results (0 = Normal, 1 = Abnormal)', [0, 1])\n",
    "thalach = st.number_input('Maximum Heart Rate Achieved', min_value=50, max_value=250, value=150)\n",
    "exang = st.selectbox('Exercise Induced Angina (1 = Yes, 0 = No)', [1, 0])\n",
    "oldpeak = st.number_input('ST Depression Induced by Exercise', min_value=0.0, max_value=10.0, value=1.0)\n",
    "slope = st.selectbox('Slope of Peak Exercise ST Segment (0 = Upsloping, 1 = Flat, 2 = Downsloping)', [0, 1, 2])\n",
    "ca = st.number_input('Number of Major Vessels Colored by Fluoroscopy (0-3)', min_value=0, max_value=3, value=0)\n",
    "thal = st.selectbox('Thalassemia (1 = Normal, 2 = Fixed Defect, 3 = Reversible Defect)', [1, 2, 3])\n",
    "\n",
    "# Collect the inputs into a list\n",
    "input_features = [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal]\n",
    "\n",
    "# Prediction Button\n",
    "if st.button('Predict'):\n",
    "    result = predict_heart_disease(input_features)\n",
    "    st.write(f'The model predicts: {result}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f53d7a3d-00b7-45ed-b4f5-1a48f804736e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"800\"\n",
       "            height=\"600\"\n",
       "            src=\"http://localhost:8501\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x1c184485ac0>"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from IPython.display import IFrame\n",
    "\n",
    "IFrame(src=\"http://localhost:8501\", width=800, height=600)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "6f33c94d-1083-41a1-bb4e-87c37e5de38c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "'streamlit' is not recognized as an internal or external command,\n",
      "operable program or batch file.\n"
     ]
    }
   ],
   "source": [
    "!streamlit run app.py\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "877862da-6bde-48d0-a7ce-160a5a7ed227",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
